# This is the spawn table for each wave
waves:
  wave1:
    vlgr: 2
    zomb: 6
    husk: 0
    wskl: 0
    brut: 0
    vind: 0
    spid: 0
    cspd: 0
    wtch: 0
    skel: 0
    stry: 0
    blze: 0
    ghst: 0
    pill: 0
    slim: 0
    mslm: 0
    crpr: 0
    phtm: 0
    evok: 0
    hgln: 0
    rvgr: 0
    wthr: 0
  wave2:
    vlgr: 3
    zomb: 9
    husk: 0
    wskl: 0
    brut: 0
    vind: 0
    spid: 0
    cspd: 0
    wtch: 0
    skel: 0
    stry: 0
    blze: 0
    ghst: 0
    pill: 0
    slim: 0
    mslm: 0
    crpr: 0
    phtm: 0
    evok: 0
    hgln: 0
    rvgr: 0
    wthr: 0
  wave3:
    vlgr: 3
    zomb: 15
    husk: 0
    wskl: 0
    brut: 0
    vind: 0
    spid: 0
    cspd: 0
    wtch: 0
    skel: 0
    stry: 0
    blze: 0
    ghst: 0
    pill: 0
    slim: 0
    mslm: 0
    crpr: 0
    phtm: 0
    evok: 0
    hgln: 0
    rvgr: 0
    wthr: 0
  wave4:
    vlgr: 4
    zomb: 10
    husk: 0
    wskl: 0
    brut: 0
    vind: 0
    spid: 5
    cspd: 0
    wtch: 0
    skel: 5
    stry: 0
    blze: 0
    ghst: 0
    pill: 0
    slim: 0
    mslm: 0
    crpr: 0
    phtm: 0
    evok: 0
    hgln: 0
    rvgr: 0
    wthr: 0
  wave5:
    vlgr: 5
    zomb: 15
    husk: 0
    wskl: 0
    brut: 0
    vind: 0
    spid: 5
    cspd: 0
    wtch: 0
    skel: 7
    stry: 0
    blze: 0
    ghst: 0
    pill: 0
    slim: 0
    mslm: 0
    crpr: 0
    phtm: 0
    evok: 0
    hgln: 0
    rvgr: 0
    wthr: 0
  wave6:
    vlgr: 7
    zomb: 18
    husk: 0
    wskl: 0
    brut: 0
    vind: 0
    spid: 7
    cspd: 0
    wtch: 0
    skel: 10
    stry: 0
    blze: 0
    ghst: 0
    pill: 0
    slim: 0
    mslm: 0
    crpr: 0
    phtm: 0
    evok: 0
    hgln: 0
    rvgr: 0
    wthr: 0
  wave7:
    vlgr: 9
    zomb: 15
    husk: 5
    wskl: 0
    brut: 0
    vind: 0
    spid: 10
    cspd: 0
    wtch: 0
    skel: 10
    stry: 0
    blze: 0
    ghst: 0
    pill: 0
    slim: 5
    mslm: 0
    crpr: 0
    phtm: 0
    evok: 0
    hgln: 0
    rvgr: 0
    wthr: 0
  wave8:
    vlgr: 12
    zomb: 10
    husk: 10
    wskl: 0
    brut: 0
    vind: 0
    spid: 10
    cspd: 0
    wtch: 0
    skel: 12
    stry: 0
    blze: 0
    ghst: 0
    pill: 0
    slim: 5
    mslm: 0
    crpr: 4
    phtm: 0
    evok: 0
    hgln: 0
    rvgr: 0
    wthr: 0
  wave9:
    vlgr: 14
    zomb: 5
    husk: 15
    wskl: 0
    brut: 0
    vind: 0
    spid: 12
    cspd: 3
    wtch: 0
    skel: 15
    stry: 0
    blze: 0
    ghst: 0
    pill: 0
    slim: 5
    mslm: 0
    crpr: 4
    phtm: 0
    evok: 0
    hgln: 0
    rvgr: 0
    wthr: 0
  wave10:
    vlgr: 16
    zomb: 0
    husk: 20
    wskl: 0
    brut: 0
    vind: 0
    spid: 7
    cspd: 8
    wtch: 0
    skel: 10
    stry: 5
    blze: 0
    ghst: 0
    pill: 5
    slim: 5
    mslm: 0
    crpr: 5
    phtm: 0
    evok: 0
    hgln: 0
    rvgr: 0
    wthr: 0
  wave11:
    vlgr: 18
    zomb: 0
    husk: 20
    wskl: 0
    brut: 0
    vind: 0
    spid: 0
    cspd: 15
    wtch: 0
    skel: 5
    stry: 10
    blze: 0
    ghst: 0
    pill: 5
    slim: 10
    mslm: 0
    crpr: 5
    phtm: 0
    evok: 0
    hgln: 0
    rvgr: 0
    wthr: 0
  wave12:
    vlgr: 20
    zomb: 0
    husk: 20
    wskl: 0
    brut: 0
    vind: 0
    spid: 0
    cspd: 15
    wtch: 0
    skel: 0
    stry: 10
    blze: 0
    ghst: 0
    pill: 10
    slim: 10
    mslm: 0
    crpr: 5
    phtm: 0
    evok: 0
    hgln: 0
    rvgr: 0
    wthr: 0

# This is the config version for reference.
# DO NOT EDIT VALUE.
version: 3

# This is the data.yml structure version for reference.
# ONLY EDIT ONCE DATA FILE HAS BEEN UPDATED.
data: 4