main: me.theguyhere.villagerdefense.Main
name: VillagerDefense
version: 0.3.0
author: Theguyhere
api-version: 1.16
depend: [HolographicDisplays]

commands:
  vd:
    description: Opens up the admin panel for Villager Defense
    usage: /vd
    permission: vd.use
    help:
      description: Redirects players to the Villager Defense wiki
      usage: /vd help
    leave:
      description: Removes players from arenas and teleports them to the lobby
      usage: /vd leave
