main: me.theguyhere.villagerdefense.Main
name: VillagerDefense
version: 0.6.1
author: Theguyhere
api-version: 1.16
depend: [HolographicDisplays]

commands:
  vd:
    admin:
      description: Opens up the admin panel for Villager Defense
      usage: /vd admin
      permission: vd.use
    help:
      description: Redirects players to the Villager Defense wiki
      usage: /vd help
    leave:
      description: Removes players from arenas and teleports them to the lobby
      usage: /vd leave
    stats:
      description: Displays stats of a player
      usage: /vd stats
    kits:
      description: Displays kits of the player
      usage: /vd kits
    select:
      description: Displays kits for the player to select for an arena
      usage: /vd select
    crystals:
      description: Changes the crystal balance of players
      usage: /vd crystals
      permission: vd.crystals